[package]
name = "cv_new_site"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1"
leptos = { version = "0.6", features = ["csr"] }
log = "0.4"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
